language: generic 
sudo: required
services:
  - docker


before_install:
  - docker build -t snehasis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true snehasis/docker-react npm run test